export const BLOOD_GROUPS = [
    'A+',
    'A-',
    'B+',
    'B-',
    'AB+',
    'AB-',
    'O+',
    'O-'
];

export const COMPONENT_TYPES = [
    'WHOLE_BLOOD',
    'PRBC',
    'PLATELETS',
    'PLASMA'
];

export const UNIT_STATUSES = {
    AVAILABLE: 'AVAILABLE',
    RESERVED: 'RESERVED',
    USED: 'USED',
    EXPIRED: 'EXPIRED',
    DISCARDED: 'DISCARDED'
};

export const UNIT_STATUS_LIST = Object.values(UNIT_STATUSES);

export const TRANSACTION_OPERATIONS = {
    ADD: 'ADD',
    UPDATE: 'UPDATE',
    RESERVE: 'RESERVE',
    ISSUE: 'ISSUE',
    USE: 'USE',
    DISCARD: 'DISCARD',
    EXPIRE: 'EXPIRE'
};

export const TRANSACTION_OPERATION_LIST = Object.values(TRANSACTION_OPERATIONS);

export const ALERT_TYPES = {
    CRITICAL_STOCK: 'CRITICAL_STOCK',
    LOW_STOCK: 'LOW_STOCK',
    EXPIRING_SOON: 'EXPIRING_SOON',
    EXPIRED: 'EXPIRED'
};

export const ALERT_TYPE_LIST = Object.values(ALERT_TYPES);

export const ALERT_SEVERITIES = {
    CRITICAL: 'CRITICAL',
    WARNING: 'WARNING',
    INFO: 'INFO'
};

export const ALERT_STATUSES = {
    ACTIVE: 'ACTIVE',
    RESOLVED: 'RESOLVED',
    ACKNOWLEDGED: 'ACKNOWLEDGED'
};

export const RECOMMENDATION_TYPES = {
    REPLENISH_STOCK: 'REPLENISH_STOCK',
    PRIORITIZE_EXPIRING: 'PRIORITIZE_EXPIRING',
    MONITOR_STOCK: 'MONITOR_STOCK',
    HIGH_DEMAND: 'HIGH_DEMAND',
    EXCESS_STOCK: 'EXCESS_STOCK',
    EXPIRY_RISK: 'EXPIRY_RISK',
    DATA_WARNING: 'DATA_WARNING',
    REPLENISH_LOW_STOCK: 'REPLENISH_LOW_STOCK',
    REVIEW_CRITICAL_STOCK: 'REVIEW_CRITICAL_STOCK',
    PRIORITIZE_EXPIRING_UNITS: 'PRIORITIZE_EXPIRING_UNITS',
    REDISTRIBUTE_INVENTORY: 'REDISTRIBUTE_INVENTORY'
};

export const RECOMMENDATION_STATUSES = {
    ACTIVE: 'ACTIVE',
    ACKNOWLEDGED: 'ACKNOWLEDGED',
    RESOLVED: 'RESOLVED',
    ACTIONED: 'ACTIONED',
    DISMISSED: 'DISMISSED'
};

export const RECOMMENDATION_PRIORITIES = {
    CRITICAL: 'CRITICAL',
    URGENT: 'URGENT',
    HIGH: 'HIGH',
    MEDIUM: 'MEDIUM',
    LOW: 'LOW'
};

export const USER_ROLES = [
    'ADMIN',
    'STAFF'
];